name: Preencher Datas Editais

on:
  workflow_dispatch:

jobs:
  preencher_datas:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      
      - name: Instalar dependÃªncias
        run: pip install requests

      - name: Preencher datas
        env:
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_KEY: ${{ secrets.SUPABASE_KEY }}
        run: python PREENCHER_DATAS.py
